from . import res_partner
from . import medical_codes
from . import medical_aid_plan
from . import product_template
from . import calendar_event
from . import clinic_examination
from . import account_invoice
from . import payment_term
from . import project_task
from . import res_config_settings
from . import purchase_order
from . import stock_picking
from . import product_category
from . import clinical_final_rx_contact
from . import res_users
from . import hway
from . import medical_aid_confrimations
from . import product_pricelist_item
from . import account_partner_ledger_inherit
